import type { Issue, Plan, Profile } from "@contracts/types";

/**
 * Exportación del plan en Markdown "LLM-friendly":
 * texto estructurado para humanos y agentes (Claude Code, OpenCode…)
 * + bloque ```json con el estado completo para reimportarlo en otro navegador.
 */

export interface ExportState {
  profile: Profile | null;
  projectId: string | null;
  projectName: string;
  issue: Issue | null;
  plan: Plan;
  doneWeeks: number[];
  exportedAt: string;
}

export function buildPlanMarkdown(state: ExportState, locale: "es" | "en"): string {
  const { plan, profile, issue, doneWeeks } = state;
  const L = locale === "es";

  const lines: string[] = [];
  lines.push(`# 21 Weeks to Bitcoin OSS — ${plan.projectName}`);
  lines.push("");
  lines.push(
    L
      ? `> Plan de 21 semanas generado por 21weeks (mentor IA autor-primero). Este archivo es legible por humanos y por LLMs: si se lo das a un agente (Claude Code, OpenCode, etc.), úsalo como contexto y respeta la regla central: **la persona escribe el código, los tests y los PRs; el agente guía, pregunta y revisa — nunca hace el trabajo por ella**.`
      : `> 21-week plan generated by 21weeks (author-first AI mentor). This file is readable by humans and LLMs: if you hand it to an agent (Claude Code, OpenCode, etc.), use it as context and respect the core rule: **the person writes the code, the tests and the PRs; the agent guides, asks and reviews — never does the work for them**.`,
  );
  lines.push("");
  lines.push(`- ${L ? "Proyecto" : "Project"}: **${plan.projectName}**`);
  if (profile) {
    lines.push(
      `- ${L ? "Perfil" : "Profile"}: ${profile.role} · ${profile.level} · ${profile.languages.join(", ")} · ${profile.hoursPerWeek} h/${L ? "semana" : "week"}`,
    );
    lines.push(`- ${L ? "Intereses" : "Interests"}: ${profile.tracks.join(", ")}`);
  }
  if (issue) {
    lines.push(`- ${L ? "Issue ancla" : "Anchor issue"}: [#${issue.number} ${issue.title}](${issue.url})`);
  }
  lines.push(`- ${L ? "Generado" : "Generated"}: ${plan.generatedAt.slice(0, 10)}`);
  lines.push(`- ${L ? "Progreso al exportar" : "Progress at export"}: ${doneWeeks.length}/21 ${L ? "semanas" : "weeks"}`);
  lines.push("");
  lines.push(`## ${L ? "Introducción" : "Introduction"}`);
  lines.push("");
  lines.push(plan.intro);
  lines.push("");
  lines.push(`## ${L ? "Las 21 semanas" : "The 21 weeks"}`);
  lines.push("");

  for (const w of plan.weeks) {
    const done = doneWeeks.includes(w.week);
    lines.push(`### [${done ? "x" : " "}] ${L ? "Semana" : "Week"} ${w.week} — ${w.phase}: ${w.title}`);
    lines.push("");
    lines.push(`**${L ? "Objetivos" : "Objectives"}**`);
    w.objectives.forEach((o) => lines.push(`- ${o}`));
    lines.push("");
    lines.push(`**${L ? "Tareas" : "Tasks"}**`);
    w.tasks.forEach((task) => lines.push(`- [ ] ${task}`));
    if (w.resources.length > 0) {
      lines.push("");
      lines.push(`**${L ? "Recursos" : "Resources"}**`);
      w.resources.forEach((r) => lines.push(`- [${r.label}](${r.url})`));
    }
    lines.push("");
    lines.push(`**${L ? "Entregable" : "Deliverable"}**: ${w.outcome}`);
    lines.push("");
  }

  lines.push(`## ${L ? "Graduación — semana 21" : "Graduation — week 21"}`);
  lines.push("");
  lines.push(plan.graduation);
  lines.push("");
  lines.push("---");
  lines.push(
    L
      ? "El bloque siguiente contiene el estado completo para reimportar este plan en 21weeks (botón «Importar plan»). No lo edites a mano."
      : "The following block holds the full state to reimport this plan into 21weeks («Import plan» button). Do not edit by hand.",
  );
  lines.push("");
  lines.push("```json21weeks");
  lines.push(JSON.stringify(state, null, 2));
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

/** Extrae el estado del bloque ```json21weeks de un .md exportado. */
export function parseImportedPlan(markdown: string): ExportState | null {
  const m = markdown.match(/```json21weeks\s*([\s\S]*?)```/);
  if (!m) return null;
  try {
    const parsed = JSON.parse(m[1]) as ExportState;
    if (!parsed.plan?.weeks?.length) return null;
    return parsed;
  } catch {
    return null;
  }
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
